### PR TITLE
Fix dset module vulnerability

### PR DESCRIPTION
**Pull request by AlexHladin**
The dset module has a vulnerability in version 2.0.1. A detailed description is available [here](https://github.com/advisories/GHSA-23wx-cgxq-vpwx).
This PR updates dset module to version 3.1.2.

### CODE REVIEW

**Comment by vweevers** [comment]
It seems to me that the vulnerability only applies to `require('dset/merge')` which isn't used here?

**Comment by AlexHladin** [comment]
> It seems to me that the vulnerability only applies to `require('dset/merge')` which isn't used here?

maybe, but `npm audit` thinks that this is set
image

**Comment by vweevers** [comment]
I'm sorry, but the burden of proof is on you. "Maybe" isn't good enough, because you're asking a volunteer to spend time on a non-issue. The proper action is to ask npm (and the rest of the security theater) for the ability to mark false positives.

**Comment by AlexHladin** [comment]
I am the same volunteer either, and just want to use the module without vulnerability. All work has already been done in the PR, tests are passing.

**Comment by vweevers** [comment]
> All work has already been done in the PR

You didn't review the vulnerability. The fix requires a semver-major update, so will have to review what changed. Etc.

**Pull request closed without merging**
