### PR TITLE
Update links to Presto website

### PR DESCRIPTION
**Pull request by martint**

### CODE REVIEW

**Comment by vweevers** [comment]
I'm not keen on supporting two variants of Presto; is there an intent to keep the HTTP protocols (v1 and the future v2) compatible?

**Comment by vweevers** [comment]
~I'm hoping https://github.com/prestosql/presto/issues/380#issuecomment-508638458 can be clarified; otherwise this feels very much like a hijacking.~

**Comment by vweevers** [comment]
Before this, I would like to:

- [ ] Check with a client of mine which codebase they use
- [x] Update the [`shawnzhu/prestodb`](https://hub.docker.com/r/shawnzhu/prestodb/) docker image (which I see recently switched to prestosql)
- [x] Run some (external) tests

**Comment by martint** [comment]
There's an official docker image for the project now, in case you want to use that: https://hub.docker.com/r/prestosql/presto. It doesn't have the Hive connector pre-configured, but it comes with the TPC-H, TPC-DS and memory connectors out of the box. Those might be sufficient to run the integration tests and would simplify your setup.

**Pull request merged**
